### ISSUE TITLE
Omnigator does not load sources with German umlauts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#206]
```
The Omnigator does not load files which contain umlauts in the file name.

(Win Vista 62bit, Firefox 3.6)
```

Original issue reported on code.google.com by `lars.he...@gmail.com` on 14 Feb 2010 at 9:24

Attachments:
* [töpüc-mäp.ctm](https://storage.googleapis.com/google-code-attachments/ontopia/issue-206/comment-0/töpüc-mäp.ctm)

**Comment by qsiebers** [comment]
Updating to java 7 has **not** fixed this issue. This issue is caused by the fact that [Tomcat decodes URI parameters as ISO-8859-1 by default](http://wiki.apache.org/tomcat/FAQ/CharacterEncoding). Either parsing the parameter as ISO-8859-1 and converting it to UTF-8, or by telling Tomcat to use UTF-8 for URI decoding, can fix this issue.
