### ISSUE TITLE
Ontopia gives error on build

### ISSUE THREAD

**Issue by boticello** [ontopia/ontopia#551]
I cloned the repo and ran the maven command in the README:
```mvn clean install -Pontopia-distribution-tomcat```

The build failed with the following error:
```[ERROR] Failed to execute goal on project ontopia-tmrap-aar: Could not resolve dependencies for project net.ontopia:ontopia-tmrap-aar:aar:5.3.1-SNAPSHOT: The following artifacts could not be resolved: net.ontopia:ontopia-tmrap:jar:5.3.1-SNAPSHOT, net.ontopia:ontopia-navigator:jar:5.3.1-SNAPSHOT, net.ontopia:ontopia-engine:jar:5.3.1-SNAPSHOT: Could not find artifact net.ontopia:ontopia-tmrap:jar:5.3.1-SNAPSHOT```

**Comment by qsiebers** [comment]
This is caused by the `-Pontopia-distribution-tomcat` profile flag. This runs the javadoc plugin before the components are build.

You can build the project with a normal `mvn clean install`, you only need to profile for building the bundled tomcat distribution, and you can only do that after a normal build successfully finished. 

Note: during testing this, I ran into an error during the ontopoly-editor build. It can be by-passed by re-running the build from that point on with `mvn clean install -rf :ontopoly-editor`

**Comment by boticello** [comment]
Thanks. I followed both your instructions but have another error: 
```[ERROR] Failed to execute goal on project ontopoly-editor: Could not resolve dependencies for project net.ontopia:ontopoly-editor:jar:5.3.1-SNAPSHOT: Could not find artifact net.ontopia:ontopia-rdf:jar:5.3.1-SNAPSHOT -> [Help 1]```

**Comment by qsiebers** [comment]
> I followed both your instructions but have another error:

Could you send me the full output of the build, including:
- The working directory
- Java version
- Maven version

> Is there a downloadable release or is building from source the only way to get a working version?

Of course there is: https://github.com/ontopia/ontopia/releases
These releases are the fully assembled tomcat instances, ready to run.

**Comment by boticello** [comment]
Ah great. Thank you. I guess that should be obvious, but perhaps you could add the link to the README? At the moment the instructions only refer to building the software from source.

**Comment by qsiebers** [comment]
> perhaps you could add the link to the README?

Will do ;)
